pipeline {
    agent any

    stages {
        stage('Build Docker Image') {

            when{
                allOf {
                    branch 'feature/implementation-of-application'
                    changeset "**/worker/**"
                }
            }
            steps {
                git 'https://github.com/VishuPatel-27/mini-idp.git' // Clone repository containing Dockerfile
                sh 'docker build -t imv27/worker-app:${env.BUILD_TAG} apps/worker/Dockerfile' // Build Docker image using the Dockerfile in the repo
            }
        }
        stage('Push to ECR') {
            steps {
                echo 'Pushing to ECR ...'
                sh '''
                    docker push imv27/worker-app:${env.BUILD_TAG}
                '''
            }
        }        
        stage('PR and Notify') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}