version: 2.1

setup: true
parameters:
  run-vote-app-job:
    type: boolean
    default: false
  workingdir:
    type: string
    # default working directory is mini-idp/apps/vote/
    default: "./apps/worker/"
    
# Orbs is a shareable, reusable package of configuration elements (like jobs, commands, and executors) 
# that simplifies and standardizes CI/CD pipelines
orbs:
  docker: circleci/docker@3.0.1
  slack: circleci/slack@6.0.0

jobs:

  # In this stage will checkout the source code and perform
  # testing on it.
  # Have used the python docker image as executer
  checkout_and_test:

    docker:
      - image: cimg/python:3.13.7
    
    steps:
     
      - checkout # checkout source code
        # Restore pip chache
     
      - restore_cache:
          name: Restoring cache of vote application if its exist
          key: 
            - vote-app-{{ checksum "requirements.txt" }}
     
        # Install dependencies
      - run:
          name: Installing required dependencies
          command: pip install -r ./requirements.txt
        
        # saving cache for better performance
      - save_cache: 
          name: saving cache of vote application dependencies
          key: vote-app-{{ checksum "requirements.txt" }}
          paths: ~/.cache/pip

        # Running unit test     
      - run: 
          name: Running unit test 
          command: |
           mkdir -p test-results
           pytest -v --junitxml=test-results/junit.xml
      
        # upload and store test results for a build
      - store_test_results: 
          path: test-results
      
      - store_artifacts:
          path: test-results

  build_and_push:
    
    executor: docker/docker
    
    steps:
    
      # checkout a source code
      - checkout 
      
      # Enable remote docker with caching
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      
      # Building Docker image
      - run:
          name: Building docker image
          command: |
            docker build -t imv27/vote-app:${$CIRCLE_BUILD_NUM} .
      
      # Running smoke test on docker image
      - run: 
          name: Smoke testing on docker image
          command: |
            mkdir -p smoke-test-results
            docker run -d -p 80:80 --name vote-smoke-test imv27/vote-app:${$CIRCLE_BUILD_NUM}
      
      # Varifying smoke result
      - run:
          name: Wait for app readiness
          command: |
            for i in {1..10}; do
              if curl -s http://localhost:80/ > /dev/null; then
                echo "App is ready"
                exit 0
              fi
              sleep 2
            done
            echo "App failed to start"
            exit 1
      
      # Cleanup
      - run: 
         name: Removing docker containers
         command: |
            docker stop vote-smoke-test
            docker rm vote-smoke-test
      
      # upload and store test results for a build
      - store_test_results: 
          path: smoke-test-results
      
      - run: 
         name: Pushing docker image to ECR repo
         command: |
            docker push imv27/vote-app:${$CIRCLE_BUILD_NUM}

  # Sending slack notification of results
  # create a PR request on main branch
  notify_and_PR_request:
    docker:
      - image: cimg/base:current
    steps: 
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  vote-app-Workflow:
    when: << pipeline.parameters.run-vote-app-job >>
    jobs:
      - checkout_and_test:
          filters:
            branches:
              only: feature/implementation-of-application   # runs on all feature/* branches
      - build_and_push:
          filters:
            branches:
              only: feature/implementation-of-application
          requires:
            - checkout_and_test
      - notify_and_PR_request:
          context: slack-secrets
          filters:
            branches:
              only: feature/implementation-of-application
          requires:
            - build_and_push