# This file contains the Kubernetes Deployment and Service for the vote application.
# It is configured to deploy desire set of replica of the application and expose it via a Service.

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "vote-ns" }}

---

apiVersion: apps/v1
kind: Deployment
# Metadata for the Deployment object
metadata:
  name: vote-deployment
  namespace: {{ .Values.namespace | default "vote-ns" }} # Needed to change by Helm values
  labels:
    app: vote-app
# Specification of the desired behavior of the Deployment
spec:
  replicas: {{ .Values.replicaCount }} # Needed to change by Helm values
  # Label selector for pods managed by this deployment
  selector: 
    matchLabels:
      app: vote-app
  # Template for the pods managed by this deployment
  template:
    metadata:
      # Labels to be applied to the pods
      labels:
        app: vote-app
    # Specification of the pod's contents
    spec:
      # Affinity rules to spread pods across zones
      topologySpreadConstraints:
        - maxSkew: {{ .Values.topologySpreadConstraints.maxSkew | default 1 }}
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: vote-app
      containers:
      - name: vote-app-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }} # Needed to change by Helm values
        # imagePullSecrets:
        # - name: aws-ecr-secret
        # to always pull the latest image, useful during development
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80 # The port that the container listens on
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }} # Reference to a ConfigMap named "vote-configmap"
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            memory: {{ .Values.resources.requests.cpu }}
            cpu: {{ .Values.resources.requests.cpu }}


---

# This file contains the Kubernetes Service for the vote application.
# It is configured to expose the Deployment via a ClusterIP service.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} # Needed to change by Helm values
  namespace: {{ .Values.namespace }} # Needed to change by Helm values
spec:
  selector:
    # Selects pods with the label "app: vote-app"
    app: vote-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }} # The port that the service will expose
      targetPort: 80 # The port on the pod that the service will forward to
  type: {{ .Values.service.type }} # The type of service

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace | default "vote-ns" }} 
data:
  REDIS_HOST: "{{ .Values.configMap.data.REDIS_HOST | default "redis-service.redis-ns" }}"
  REDIS_PORT: "{{ .Values.configMap.data.REDIS_PORT | default "6379" }}"
  OPTION_A: "{{ .Values.configMap.data.OPTION_A | default "Cats" }}"
  OPTION_B: "{{ .Values.configMap.data.OPTION_B | default "Dogs" }}"