pipeline {
    agent {
        docker {
            image 'ubuntu:latest' // Use the official Ubuntu image from Docker Hub
            reuseNode true // Reuse the same container for all stages
        }
    }

    stages {
        stage('Build Docker Image') {

            when{
                allOf {
                    branch 'feature/implementation-of-application'
                    changeset "**/vote/**"
                }
            }
            steps {
                sh 'docker build -t imv27/vote-app:${env.BUILD_TAG} .' // Build Docker image using the Dockerfile in the repo
            }
        }
        stage('Push to ECR') {
            steps {
                echo 'Pushing to ECR ...'
                sh '''
                    docker push imv27/vote-app:${env.BUILD_TAG}
                '''
            }
        }        
        stage('PR and Notify') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}